version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"


  kafka:
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=logsdb

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092  
      - TOPIC_NAME=logs
      - LOG_FILE_PATH=/app/logs/Apache.log
    volumes:
      - ./logs:/app/logs
    
  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC_NAME=logs
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=logsdb
      - DB_USER=admin
      - DB_PASS=admin

